FROM node:12.13 As builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install 
COPY . .
RUN npm run build

FROM node:12.13-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ ./
CMD ["npm", "run", "start:prod"]